#!/usr/bin/env python3

from robonomics_msgs.msg import Demand
import rospy

def callback(msg):
    if msg.model.multihash == "QmVCPhLcGi7GussfhrCxhSb1H5FrNyrM9uR6HuLgqgwawB":
        rospy.loginfo("Hello AIRA")

if __name__ == '__main__':
    rospy.init_node('hello_aira')
    rospy.Subscriber('/liability/infochan/incoming/demand', Demand, callback)
    rospy.spin()
