#!/usr/bin/env python3

from robonomics_lighthouse.msg import Ask
import rospy

def callback(msg):
    if msg.model == "QmVCPhLcGi7GussfhrCxhSb1H5FrNyrM9uR6HuLgqgwawB":
        rospy.loginfo("Hello AIRA")

if __name__ == '__main__':
    rospy.init_node('hello_aira')
    rospy.Subscriber('/lighthouse/infochan/incoming/ask', Ask, callback)
    rospy.spin()
