export const NETWORK = 1
export const VERSION = 3
export const ENS = ''
export const LIGHTHOUSE = 'airalab.lighthouse.3.robonomics.eth'
export const MODEL = 'QmVCPhLcGi7GussfhrCxhSb1H5FrNyrM9uR6HuLgqgwawB'
export const OBJECTIVE = 'QmbSW1E73DKUvGDrgx8GirEVfHJLvj8RBijtH9iEZ7UecU'
export const IPFS_PUBSUB = 'https://wss.pool.aira.life' // https://github.com/vol4tim/ipfs-api-pubsub-ws
export const TOKEN = null
export const PRICE = 0
