export const NETWORK = 1
export const VERSION = 3
export const ENS = ''
export const LIGHTHOUSE = 'airalab.lighthouse.3.robonomics.eth'
export const MODEL = 'QmSoY8nSUMbhTQDaoqHRBSoCHNeedhsMqg1WJRS4EYTPN6'
export const OBJECTIVE = 'QmUq7d4jATFnbDgtkv83d3VW9jRqqCRkctZdGUBZE5wGN2'
export const IPFS_PUBSUB = 'http://localhost:9999/' // 'https://wss.pool.aira.life' // https://github.com/vol4tim/ipfs-api-pubsub-ws
export const TOKEN = '0x98DFc5247da729c045D4938bABD081A61a455776'
export const PRICE = 1
